# Generated by Django 4.2.5 on 2023-10-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='banner_pic',
        ),
        migrations.RemoveField(
            model_name='account',
            name='default_banner',
        ),
    ]
